fix kind load docker-image content digest not found
`kind setup` starts to fail with error:
```
ERROR: failed to load image: command "docker exec --privileged -i ovn-worker
   ctr --namespace=k8s.io images import --all-platforms --digests
   --snapshotter=overlayfs -" failed with error: exit status 1

Command Output: ctr: content digest sha256:9c04829e9...: not found
```

Related kind issue is https://github.com/kubernetes-sigs/kind/issues/3795.
This change uses the workaround mentioned in the kind issue.

Signed-off-by: Lei Huang <leih@nvidia.com>
(cherry picked from commit 2edd4307e0a6abd039d3bab16de1a46c87ab6a08)