K8s rebase 1.33.3  > go-controller
   go get k8s.io/api@v0.33.3
   go get k8s.io/client-go@v0.33.3
   go get k8s.io/component-helpers@v0.33.3
   go get k8s.io/kubernetes@v1.33.3
   go get k8s.io/apiextensions-apiserver@v0.33.3
   go get sigs.k8s.io/controller-runtime@v0.21.0
   go get k8s.io/controller-manager@v0.33.3
   go mod tidy
   go mod vendor
   make lint

   Fix typecheck errors by removing "k8s.io/utils/exec".Interface arg to function call NewController() in the files below
   pkg/node/iptables/iptables_manager.go
   pkg/node/controllers/egressip/egressip_test.go

   pkg/node/iptables/iptables_manager.go:70:36: too many arguments in call to iptables.New
	have ("k8s.io/utils/exec".Interface, "k8s.io/kubernetes/pkg/util/iptables".Protocol)
	want ("k8s.io/kubernetes/pkg/util/iptables".Protocol)
   pkg/node/iptables/iptables_manager.go:71:36: too many arguments in call to iptables.New
	have ("k8s.io/utils/exec".Interface, "k8s.io/kubernetes/pkg/util/iptables".Protocol)
	want ("k8s.io/kubernetes/pkg/util/iptables".Protocol)) (typecheck)
	"github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node/iptables"

   pkg/node/controllers/egressip/egressip_test.go:173:52: too many arguments in call to utiliptables.New
	have ("k8s.io/utils/exec".Interface, "k8s.io/kubernetes/pkg/util/iptables".Protocol)
	want ("k8s.io/kubernetes/pkg/util/iptables".Protocol) (typecheck)
		ipTableV4Client := utiliptables.New(kexec.New(), utiliptables.ProtocolIPv4)		                                                 ^
   pkg/node/controllers/egressip/egressip_test.go:174:52: too many arguments in call to utiliptables.New
	have ("k8s.io/utils/exec".Interface, "k8s.io/kubernetes/pkg/util/iptables".Protocol)
	want ("k8s.io/kubernetes/pkg/util/iptables".Protocol) (typecheck)
		ipTableV6Client := utiliptables.New(kexec.New(), utiliptables.ProtocolIPv6)

  Update golangci-lint version to 1.68.4 in test.yaml and lint.sh

  Fix staticcheck error in cmd/ovnkube-trace/ovnkube-trace.go to use endpointslice API instead of endpoints
  cmd/ovnkube-trace/ovnkube-trace.go:383:98: SA1019: corev1.EndpointSubset is deprecated: This API is deprecated in v1.33+. (staticcheck)
  func extractSubsetInfo(coreclient *corev1client.CoreV1Client, restconfig *rest.Config, subsets []corev1.EndpointSubset, svcInfo *SvcInfo, ovnNamespace, addressFamily string) error {

 > KIND
   K8s version for KIND to v1.33.1 ( v1.33.3 image is not yet available)
   Fix k8s version for KIND in .github/workflows/test.xml, contrib/kind-common, test/scripts/upgrade-ovn.sh, test/scripts/install-kind.sh, docs/ci/ci.md and docs/installation/launching-ovn-kubernetes-on-kind.md

Signed-off-by: Arti Sood <asood@redhat.com>